import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { createClient } from 'contentful';
import Image from 'next/image';
import Cards from '../components/cards';
import Box from '../components/box';

export async function getStaticProps() {

  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
  })

  const resCard = await client.getEntries({ content_type: 'card' })
  const resBox = await client.getEntries({ content_type: 'box' })

  return {
    props: {
      card: resCard.items,
      boxes: resBox.items,
    }
  }
}

export default function Home( { card, boxes }) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>        
        <Cards card={card}/>  
        <Box boxes={boxes}/>      
      </main>      
   </div>
  )
}
