import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { cards } from './cardsData';
import { createClient } from 'contentful';
import Image from 'next/image';

export async function getStaticProps() {

  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
  })

  const res = await client.getEntries({ content_type: 'card' })

  return {
    props: {
      card: res.items
    }
  }
}

export default function Home( { card }) {
  console.log(card)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>hello dogs</h1>        
        {card.map(item => (
          <div className={styles.card} key={item.fields.heading}>
            <h2>{item.fields.heading}</h2>
            <p>{item.fields.blurb}</p>
          </div>
        ))}
      </main>      
    </div>
  )
}
